apiVersion: ENC[AES256_GCM,data:LRc=,iv:kqLBEOQepnoJHIyNja386TYwq8jr/nAEJFcrHHSw6mE=,tag:3+GdB94jG3yEWNq7TmfQnQ==,type:str]
kind: ENC[AES256_GCM,data:hKsMngvP,iv:060HWCs/U5t61x7ifDuXHiXC1M3fNw2hBrAflUpBIH0=,tag:gLXj+ZBiN207gVOrEXSjAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:96bAP2pyEGuuh/aIU24X,iv:JUs1Vq0Rhyr3aGJmbAsZKtWU1R+nRiIaABLsDhWSsiQ=,tag:ZmLEWPI5mZExc3BeulobMw==,type:str]
    namespace: ENC[AES256_GCM,data:kNwqgAA5UETZ+Axvow==,iv:F6GTKpk/LLRdTI4HXDw7H+Prl6FN5Q5GVUYLcXUxS8k=,tag:6fTfBS9gC/UxHmPMTFRObg==,type:str]
type: ENC[AES256_GCM,data:EePyHTGO,iv:CL188wv0U0jwrd9Z0UzsSjXZc1m7IOvWE8jnbzy8t+0=,tag:XwjtXBQITp/PBOgEBQhtIA==,type:str]
stringData:
    #ENC[AES256_GCM,data:iUgCkrhCoUYSL7+LdYdnjg1fBzSES6wEzzkkgM0p55NwgmdGvOPReaWfdow=,iv:FHnHpu06GmxU+N+mHycj+z42PUg0+93j9br3hKN/0YM=,tag:aCgyuTTSRMLpF+vR1f1JNw==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:tk/AgThJuBiivLrF2fMkfNMyMjav86kj2GB4Q1p6drvURJ8vaYFv5Jt30gli/+k=,iv:qndfvoJXjNK3PJmBIdK6m7wCA0C3FqMVdVBdtAyb4IM=,tag:386+RENQeCLQLOa0C5wjPg==,type:str]
sops:
    age:
        - recipient: age1x6ka0u4tudyx4dsw2lc9apaejk5qvcmzx59j0ktkavfhjkepa54se0fpl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzREQrVVpCWUszUlRKbFlo
            Q1JMWVFUWk1ZUU5BZXFUN3FNdkpZUXVQb213CmJsYm9nZENjbW5IeFl3WTFETFk0
            cW1lSHhzTWFYbnZJWGEyTW1wbnVzSmcKLS0tIEh5eUpzV3pkZmowWjV3dHBsUVRx
            WkVDK09nNnJ6MW91WldqVW9Yb0EzcDgKJNFO59DXWdE2GLO7X2Ev4ebPxmYR5dHE
            Rlhm0NPwxA0SmAMiT8N0hjdoM6sJkgOtAWcIDfG1KJRG0W14A6vhkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T16:25:19Z"
    mac: ENC[AES256_GCM,data:iTfK4sOdZXpwNCMg9db7gQaIZGfhub7HE9gl/kTeTt8pg5FCM9/5ZchLXZQODwayBaI0/WULBivRkwM+HJVlOgaqVvfM/Be3XDhNlpDvvoVsipVKpTW2mrPdefopPXHdO6sdM9X+PhQS3CYfZkxVFsRIPaU1MSaFHGhWeAI8vG0=,iv:hJVFg8T8PY7i/nMT/znQAZ+njhKlsexWldCXxI147fQ=,tag:6mj5UW9cuhseTAvTJvMiqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
