apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dashboard-app
type: Opaque
stringData:
  #change in prod â€” use: openssl rand -hex 32
  JWT_SECRET: "change-me-in-production-use-openssl-rand-hex-32"
