apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - 02-backend.yaml
  - 03-frontend.yaml
  - 04-ingress.yaml

generators:
  - ksops-generator.yaml

generatorOptions:
  disableNameSuffixHash: true
